export const CleaningPackages = [
	{
		id: 3,
		packageCat: 'Cleaning Services',
		packageName: 'Deep Interior Cleaning',
		packageDetailTitle: 'Package Includes:',
		packageDetailBullets: ['Thorough Vacuum', 'Cleaning Interior Glass & Windows', 'Wiping Down Dust Of All Surfaces', 'Steam Cleaning & Shampoo ', 'Cleaning & Conditioning Leather & Trim'],
		packagePriceTitle: 'Prices:',
		packagePriceArr: ['Small Vehicle:  $35', 'Medium Vehicles: $45', 'Large Vehicles: $55', 'Extra Large Vehicles: $65'],

		packageEstimatedTimeTitle: 'Est. Time:',
		packageEstimatedTimeArr: ['Small Vehicle: 1 Hour', 'Medium Vehicle: 1.5 Hours', 'Large Vehicle: 2 Hours', 'Extra Large Vehicle: 2.5+ Hours'],
		tNailSRC: '/Assets/Images/PricingTnails/DeepInteriorCleaning.jpg',
		PackageDetailParagraph: 'Through interior cleaning and shampooing package.',
	},
	{
		id: 4,
		packageCat: 'Cleaning Services',
		packageName: 'Basic Interior Cleaning',
		packageDetailTitle: 'Package Includes:',
		packageDetailBullets: ['Thorough Vacuum', 'Wipe Down Door Jams, Cup Holders, and Center Console', 'Cleaning Interior Glass & Windows'],
		packagePriceTitle: 'Prices:',
		packagePriceArr: ['Small Vehicle:  $15', 'Medium Vehicles: $20', 'Large Vehicles: $30', 'Extra Large Vehicles: $45+'],
		packageEstimatedTimeTitle: 'Est. Time:',
		packageEstimatedTimeArr: ['Small Vehicle: 20 Minutes', 'Medium Vehicle: 30 Minutes', 'Large Vehicle: 1 Hour', 'Extra Large Vehicle: 1.5+ Hours'],
		tNailSRC: '/Assets/Images/PricingTnails/BasicCleaning.jpg',
		PackageDetailParagraph: 'Quick and affordable interior cleaning package.',
	},
	{
		id: 5,
		packageCat: 'Cleaning Services',
		packageName: 'Engine Cleaning',
		packageDetailTitle: 'Package Includes:',
		packageDetailBullets: ['Cover Sensitive Areas', 'Softly Rinse Engine Bay', 'Clean & Degrease All Surfaces', 'Dressing All Plastic & Vinyl'],
		packagePriceTitle: 'Prices:',
		packagePriceArr: ['Small Vehicle:  $20+', 'Medium Vehicles: $35+', 'Large Vehicles: $50+', 'Extra Large Vehicles: $70+'],
		packageEstimatedTimeTitle: 'Est. Time:',
		packageEstimatedTimeArr: ['Small Vehicle: 30 Minutes', 'Medium Vehicle: 1 Hour', 'Large Vehicle: 1.5 Hours', 'Extra Large Vehicle: 2+ Hours'],
		tNailSRC: '/Assets/Images/PricingTnails/EngineCleaning.jpg',
		PackageDetailParagraph: 'Complete engine and engine bay cleaning package.',
	},
];
