export const PolishPackages = [

    {
        id: 3,
        packageCat: 'Detailing Services',
        packageName: 'One Step Polish',
        packageDetailTitle: 'Package Includes:',
        packageDetailBullets: [
            'Hand wash and dry',
            'Clean wheels, tires, fenders, gas cap',
            'Clay exterior surfaces for a smooth finish',
            'Polish paintwork',
            'Apply wax/sealant',
            'Wipe down door jambs',
            'Clean exterior glass and windows',
            'Dress tires and fenders' ,
            'Dress exterior trim',
            'Clean and polish emblems',
            'Apply wax/sealant',
            'Final Wipe Down w/ Carnauba Wax'
        ],
        packagePriceTitle: 'Prices:',
        packagePriceArr: ['Small Vehicle:  $200', 'Medium Vehicles: $300+', 'Large Vehicles: $400+', 'Extra Large Vehicles: $500+'],
        packageEstimatedTimeTitle: 'Est. Time:',
        packageEstimatedTimeArr: ['Small Vehicle: 4 Housr', 'Medium Vehicle: 7 Hours', 'Large Vehicle: 10 Hours', 'Extra Large Vehicle: 10+ Hours'],
        tNailSRC: '/Assets/Images/OneStepPolish.jpg',
        PackageDetailParagraph: 'Quick and affordable exterior detailing package.',
    },
    {
        id: 4,
        packageCat: 'Detailing Services',
        packageName: 'Two Step Polish',
        packageDetailTitle: 'Package Includes:',
        packageDetailBullets: [
            'Hand wash and dry',
            'Clean wheels, tires, fenders, gas cap',
            'Clay exterior surfaces for a smooth finish',
            'Polish paintwork 80%',
            'Finish off Paint work 20%',
            'Apply wax/sealant',
            'Wipe down door jambs',
            'Clean exterior glass and windows',
            'Dress tires and fenders' ,
            'Dress exterior trim',
            'Clean and polish emblems',
            'Apply wax/sealant',
            'Final Wipe Down w/ Carnauba Wax'
        ],		
        packagePriceTitle: 'Prices:',
        packagePriceArr: ['The price for this service will depend on the current condition of the vehicle. Please call or send an email to request a quote'],
        packageEstimatedTimeTitle: 'Est. Time:',
        packageEstimatedTimeArr: ['The time for this service will depend on the current condition of the vehicle. Please call or send an email to request a quote'],
        tNailSRC: '/Assets/Images/TwoStepPolish.jpg',
        PackageDetailParagraph: 'Quick and affordable exterior detailing package.',
    },
];