export const WashPackages = [
	{
		id: 0,
		packageCat: 'Complete Package',
		packageName: 'All in One Service',
		packageDetailTitle: 'Package Includes:',
		packageDetailBullets: [
			'Hand Wash & Dry',
			'Clean Wheels, Tires, Fenders, Gas Cap',
			'Clay exterior surfaces',
			'Polish paintwork',
			'Apply wax/sealant',
			'Wipe down door jambs',
			'Clean exterior glass and windows',
			'Dress tires and fenders',
			'Dress exterior trim',
			'Clean and polish emblems',
			'Polish wheels',
			'Apply wax/sealant',
			'Final Wipe Down w/ Carnauba Wax'
		],
		packagePriceTitle: 'Prices:',
		packagePriceArr: ['Small Vehicle:  $180+', 'Medium Vehicles: $200+', 'Large Vehicles: $250+', 'Extra Large Vehicles: $300+'],
		packageEstimatedTimeTitle: 'Est. Time:',
		packageEstimatedTimeArr: ['Small Vehicle: 3.5 Hours', 'Medium Vehicle: 4+ Hours', 'Large Vehicle: 6+ Hours', 'Extra Large Vehicle: 8+ Hours'],
		tNailSRC: '/Assets/Images/PricingTnails/AllInOneCleaning.jpg',
		PackageDetailParagraph: 'All encompassing vehicle detailing package.',
	},

	{
		id: 1,
		packageCat: 'Detailing Services',
		packageName: 'Detail Wash & Wax',
		packageDetailTitle: 'Package Includes:',
		packageDetailBullets: ['Hand Wash & Dry', 'Clay exterior surfaces', 'Apply Wax/Sealant', 'Wipe Down Door Jambs', 'Clean Exterior Glass & Windows', 'Dress Tires & Fenders', 'Dress Exterior Trim', 'Paint Decontamination', 'Dress Exterior Trims', 'Final Wipe Down w/ Carnauba Wax'],
		packagePriceTitle: 'Prices:',
		packagePriceArr: ['Small Vehicle:  $75 - $80', 'Medium Vehicles: $85 - $90', 'Large Vehicles: $95 - 100', 'Extra Large Vehicles: $110+'],
		packageEstimatedTimeTitle: 'Est. Time:',
		packageEstimatedTimeArr: ['Small Vehicle: 1.5+ Hours', 'Medium Vehicle: 2.5+ Hours', 'Large Vehicle: 4.5+ Hours', 'Extra Large Vehicle: 6+ Hours'],

		tNailSRC: '/Assets/Images/PricingTnails/DetailWashNWax.jpg',
		PackageDetailParagraph: 'Specialized vehicle exterior detailing package.',
	},
	{
		id: 2,
		packageCat: 'Detailing Services',
		packageName: 'Express Detail',
		packageDetailTitle: 'Package Includes:',
		packageDetailBullets: ['Hand Wash & Dry', 'Clean Wheels, Tires, Fenders, Gas Cap', 'Wipe Down Door Jambs', 'Clean Exterior Glass & Windows', 'Dress Tires',  'Final Wipe Down w/ Carnauba Wax '],
		packagePriceTitle: 'Prices:',
		packagePriceArr: ['Small Vehicle:  $35', 'Medium Vehicles: $45', 'Large Vehicles: $55', 'Extra Large Vehicles: $65'],
		packageEstimatedTimeTitle: 'Est. Time:',
		packageEstimatedTimeArr: ['Small Vehicle: 1 Hour', 'Medium Vehicle: 1.5 Hours', 'Large Vehicle: 2 Hours', 'Extra Large Vehicle: 2.5+ Hours'],
		tNailSRC: '/Assets/Images/PricingTnails/ExpressDetail.jpg',
		PackageDetailParagraph: 'Quick and affordable exterior detailing package.',
	},
	
];
