export const WashPackages = [
	{
		id: 0,
		packageCat: 'Complete Package',
		packageName: 'All in One Service',
		packageDetailTitle: 'Package Includes:',
		packageDetailBullets: [
			'Hand Wash & Dry',
			'Clean Wheels, Tires, Fenders, Gas Cap',
			'Clay exterior surfaces',
			'Polish paintwork',
			'Apply wax/sealant',
			'Wipe down door jambs',
			'Clean exterior glass and windows',
			'Dress tires and fenders',
			'Dress exterior trim',
			'Clean and polish emblems',
			'Polish wheels',
			'Apply wax/sealant',
			'Final Wipe Down w/ Carnauba Wax',
		],
		packagePriceTitle: 'Prices:',
		packagePriceArr: ['The price for this service will depend on the current condition of the vehicle. Please call or send an email to request a quote'],
		packageEstimatedTimeTitle: 'Est. Time:',
		packageEstimatedTimeArr: ['The time for this service will depend on the current condition of the vehicle. Please call or send an email to request a quote'],
		tNailSRC: '/Assets/Images/PricingTnails/AllInOneCleaning.jpg',
		PackageDetailParagraph: 'All encompassing vehicle detailing package.',
	},

	{
		id: 1,
		packageCat: 'Detailing Services',
		packageName: 'Detail Wash & Wax',
		packageDetailTitle: 'Package Includes:',
		packageDetailBullets: ['Hand Wash & Dry', 'Clay exterior surfaces', 'Apply Wax/Sealant', 'Wipe Down Door Jambs', 'Clean Exterior Glass & Windows', 'Dress Tires & Fenders', 'Dress Exterior Trim', 'Paint Decontamination', 'Dress Exterior Trims', 'Final Wipe Down w/ Carnauba Wax'],
		packagePriceTitle: 'Prices:',
		packagePriceArr: ['The price for this service will depend on the current condition of the vehicle. Please call or send an email to request a quote'],
		packageEstimatedTimeTitle: 'Est. Time:',
		packageEstimatedTimeArr: ['The time for this service will depend on the current condition of the vehicle. Please call or send an email to request a quote'],

		tNailSRC: '/Assets/Images/PricingTnails/DetailWashNWax.jpg',
		PackageDetailParagraph: 'Specialized vehicle exterior detailing package.',
	},
	{
		id: 2,
		packageCat: 'Detailing Services',
		packageName: 'Express Detail',
		packageDetailTitle: 'Package Includes:',
		packageDetailBullets: ['Hand Wash & Dry', 'Clean Wheels, Tires, Fenders, Gas Cap', 'Wipe Down Door Jambs', 'Clean Exterior Glass & Windows', 'Dress Tires', 'Final Wipe Down w/ Carnauba Wax '],
		packagePriceTitle: 'Prices:',
		packagePriceArr: ['The price for this service will depend on the current condition of the vehicle. Please call or send an email to request a quote'],
		packageEstimatedTimeTitle: 'Est. Time:',
		packageEstimatedTimeArr: ['The time for this service will depend on the current condition of the vehicle. Please call or send an email to request a quote'],
		tNailSRC: '/Assets/Images/PricingTnails/ExpressDetail.jpg',
		PackageDetailParagraph: 'Quick and affordable exterior detailing package.',
	},
];
